package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Project93062_Build'
in the project with id = 'Project93062', and delete the patch script.
*/
create(RelativeId("Project93062"), BuildType({
    id("Project93062_Build")
    name = "Build"

    params {
        param("teamcity.tool.mavena", "%teamcity.tool.maven.DEFAULT%")
    }

    steps {
        step {
            type = "Projectparent_ProjectMaven_Recipe1"
            executionMode = BuildStep.ExecutionMode.DEFAULT
            param("env.PATH", "%env.PATH%:%teamcity.tool.mavena%/bin")
        }
    }
}))

